import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import styles from '@/styles/TodoApp.module.css'
import Link from 'next/link'
import {useEffect, useState} from "react";
import { useRouter } from 'next/router'
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
  useUser,
  RedirectToSignIn,
  useSession,
} from "@clerk/clerk-react";

// const clerk_pub_key = process.env.REACT_APP_CLERK_PUBLISHABLE_KEY;

const clerk_pub_key ="pk_test_c3Rhci1odXNreS0zMi5jbGVyay5hY2NvdW50cy5kZXYk"

export default function Home() {
  let router = useRouter()

  const [login, setLogin] = useState(false)

  function Hello() {
    return <div>Hello from Clerk</div>;
  }

  function signIn()
  {
    console.log("click")
    setLogin(true)
  }

  function Redirect() {
    router.push('/todos')
  }

  return (
    <>
      <Head>
         <title>home page</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
     </Head>
     <ClerkProvider publishableKey={clerk_pub_key}>
      <SignedIn>
        <Redirect />
      </SignedIn>
      <SignedOut>
        <h1>Rays todo app</h1>
        <button onClick={signIn}>Login or Signup</button>
        {login && (
          <RedirectToSignIn />
        )}
      </SignedOut>
    </ClerkProvider>
    </>
  )
}
