import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import styles from '@/styles/TodoApp.module.css'
import Link from 'next/link'
import {useEffect, useState} from "react";
import { useRouter } from 'next/router'
import { useAuth } from "@clerk/nextjs";
import { addUser } from '@/modules/Data'
import {
  // ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
  useUser,
  RedirectToSignIn,
  useSession,
} from "@clerk/clerk-react";

// const clerk_pub_key = process.env.REACT_APP_CLERK_PUBLISHABLE_KEY;

export default function Home() {
  let router = useRouter()
  const { isLoaded, isSignedIn, user } = useUser();
  const {getToken} = useAuth();


  const [login, setLogin] = useState(false)

  function signIn()
  {
    setLogin(true)
  }

  function Redirect() {
      router.push('/todos')
  }

  async function AddUser()
  {
    if(isLoaded)
    { 
      //use useuser to get user info such as id, use use auth to get token from clerk
      const newUser = {
        "username": user.fullName,
        "_id":user.id,
      }
      const token = await getToken({template: "codehooks"});
      let res = await addUser(token, newUser);
      console.log(res);
    }
  }

  function AddUser() {
    async function addUserDB() {
      if(isLoaded)
      { 
        const newUser = {
          "username": user.fullName,
          "_id":user.id,
        }
        const token = await getToken({template: "codehooks"});
        await addUser(token, newUser);
      }
    }
    addUserDB();
  }

  return (
    <>
      <Head>
          <title>home page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
        <SignedIn>
          <AddUser />
          <Redirect />
        </SignedIn>
        <SignedOut>
          <h1>Rays todo app</h1>
          <button onClick={signIn}>Login or Signup</button>
          {login && (
            <RedirectToSignIn />
          )}
        </SignedOut>
    </>
  )
}
