import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPen, faFloppyDisk, faArrowLeft} from "@fortawesome/free-solid-svg-icons";
import Head from 'next/head'
import { updateTodoItem, getTodoItem} from "@/modules/Data";
import { useAuth } from "@clerk/nextjs";
import { TailSpin } from 'react-loading-icons'
export default function TodoItem() {
    const [editing, setEditing] = useState(false);
    const [todoItem, setTodoItem] = useState({});
    const [loading, setLoading] = useState(true);
    const [saveLoading, setSaveLoading] = useState(false);
    const [updatedText, setUpdatedText] = useState("");
    const [isVisible, setVisibility] = useState(false);
    const router = useRouter();
    const {getToken, userId, isLoaded } = useAuth()

    useEffect(() => {
        if(isLoaded) {
            if (!userId) {
                router.push("/");
            }
        }
    }, [isLoaded])

    useEffect(() => {
        //router.isReady prevents query from being undefined on page reload
        //along with adding dependency to the useEffect dependency list
        if(router.isReady){
            //get the id from the route
            const { id } = router.query;

            async function getItem() {
                const token = await getToken({template: "codehooks"});
                let data = await getTodoItem(token, id);
                setTodoItem(data[0]);
                setLoading(false);
            }
            getItem();
        }
    }, [router.isReady])

    function toggleEditing() {
        setEditing(!editing)
    }

    async function saveEdit() {
        const update = {
            "status": todoItem.status,
            "createdOn": todoItem.createdOn,
            "category": todoItem.category,
            "text": updatedText,
            "userId": todoItem.userId,
            "_id": todoItem._id
        }

        const token = await getToken({template: "codehooks"});
        setSaveLoading(true);
        await updateTodoItem(token,todoItem._id, update);
        setSaveLoading(false);
        setVisibility(true);
        setTimeout(() => {
            setVisibility(false);
        }, 3000)
    }

    if(loading)
    {
         return (
             <span>loading....</span>
         )
    }
    return (
        <>
            <Head>
                <title>Todo Item</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <div className="todoItemPageContainer">
            <div className="pageHeader">
                <span>Edit Page</span>
            </div>
            {!editing && (
                <div className="nonEditText">
                    <p>{todoItem.text}</p>
                </div>
            )}
            {editing && (
                <div className="editText">
                    <textarea className="todoItemTextInput" placeholder="todo item description" onChange={(e) => setUpdatedText(e.target.value)}>{todoItem.text}</textarea>
                </div>
            )}
            <div className="todoItemButtonsContainer">
                <button className="todoItemButton" title="Back to todos" onClick={() => router.back()}>
                    <FontAwesomeIcon icon={faArrowLeft} className="buttonIcon"/>
                </button>
                <button className="todoItemButton" onClick={toggleEditing} title="Toggle Editing">
                    <FontAwesomeIcon icon={faPen} className="buttonIcon"/>
                </button>
                {editing && (<button className="todoItemButton" onClick={saveEdit} title="Save Edit">
                    <FontAwesomeIcon icon={faFloppyDisk} className="buttonIcon"/>
                </button>)}
            </div>
            <div>
                {saveLoading && (
                    <TailSpin stroke="#000000" fill="#000000" strokeOpacity={1} />
                )}
                {isVisible && (
                    <div className="editConfirmation">
                        <p>Edit Successful</p>
                    </div>
                )}
            </div>
        </div>
        </>
    )
}

