import {useEffect, useState} from "react";
import TodoItem from "@/components/todoItem";
import PageHeader from "@/components/header";
import Head from 'next/head'
import { getTodoItemsCategory } from "@/modules/Data";
import { useAuth } from "@clerk/nextjs";
import { useRouter } from "next/router";
import CategoryList from "@/components/categoryList";
import NoData from "@/components/noData";

export default function DoneCategoryPage() {
    const router = useRouter();
    const [todoList, setTodoList] = useState([]);
    const [loading, setLoading] = useState(true);
    const { isLoaded, userId, sessionId, getToken } = useAuth();
    const [category, setCategory] = useState("");

    useEffect(() => {
        if(isLoaded) {
            if (!userId) {
                router.push("/");
            }
        }
    }, [isLoaded])

    useEffect(()=>{
        if(router.isReady) {
            setCategory(router.query.category);
            async function loadData() {
                const token = await getToken({template: "codehooks"});
                let data = await getTodoItemsCategory(token, userId, category);
                setTodoList(data)
                setLoading(false);
            }
            loadData();
        }
    }, [todoList, isLoaded, router.isReady]);

   if(loading)
   {
        return (
            <>
                <div>
                    <PageHeader pageTitle={`Done`} />
                </div>
                <span>loading....</span>
            </>
        )
   }

    return (
        <>
            <Head>
                <title>Todos</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='todoPageContainer'>
                <div>
                    <PageHeader pageTitle={`Done`} />
                </div>
                <div>
                    <CategoryList status={"done"}/>
                </div>
                <div className="todoItems">
                    {category && (
                        <div className="categoryHeader">
                            <span>{`Category: ${category}`}</span>
                        </div>
                    )}
                     {!category && (
                        <div className="categoryHeader">
                            <span>{`Category: None`}</span>
                        </div>
                    )}
                    {todoList.length === 0 && (
                        <NoData />
                    )}
                    <div>
                        {todoList.map(todos => (
                            <TodoItem key={todos.id} item={todos}></TodoItem>
                        ))}
                    </div>
                </div>
            </div>
        </>
    )
}

